name: Tests
on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Merge changes into develop
        run: |
          # Get the name of the branch that triggered the workflow
          echo "Merging changes from ${GITHUB_REF#refs/heads/} into develop"
          git fetch origin ${GITHUB_REF#refs/heads/}
          git merge origin/${GITHUB_REF#refs/heads/}
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.15
      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install -r requirements.txt
          echo requirements installed
        # pip uninstall bson
        # pip uninstall pymongo
        # pip install pymongo
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: |
          python -m pytest tests
